= HTTP 2 CLI
:source-highlighter: highlightjs
:source-language: sh-session
:source-linenums-option: 1

image:https://img.shields.io/github/v/release/VEuPathDB/util-http2cli[GitHub release (latest SemVer)]
image:https://img.shields.io/github/go-mod/go-version/VEuPathDB/util-http2cli?label=go[GitHub go.mod Go version]
image:https://github.com/VEuPathDB/util-http2cli/workflows/Build/badge.svg[Build]
image:https://codecov.io/gh/VEuPathDB/util-http2cli/branch/main/graph/badge.svg?token=J4gqy0CBwb[title=codecov, link=https://codecov.io/gh/VEuPathDB/util-http2cli]

A simple HTTP server allowing access to explicitly defined CLI commands on the
host machine (or container).

This tool's default use case and default setup are targeted towards running
a select set of tools in the `ncbi/blast` docker container.

Job output is written to the host filesystem, and must be exposed through other
means if outside access is required.  The intended use case is for consumer
services to read from the job directory either via a local directory, or a
mounted volume.

== Usage

.Help Output
[source, sh-session]
----
$ ./http2cli -h
Usage:
  http2cli [OPTIONS]

Options
  -t <cmd>  | --tools=<cmd>     List of tools this service is allowed to call.

                                This list may be specified by using this flag more than once.

                                Defaults to [blastn, blastp, blastx, tblastn, tblastx].
  -d <path> | --db-dir=<path>   Root directory this service will use as the base path when
                                configuring a blast tool run.

                                This should match the volume mount point set when starting the
                                docker container.

                                Defaults to /db
  -o <path> | --out-dir=<path>  Output directory this service will use as the base path when
                                configuring a blast tool run.

                                This should match the volume mount point set when starting the
                                docker container.

                                Defaults to /out
  -p <port> | --port=<port>     Port the HTTP server should bind to.
  -V        | --version


Help & Info
  -h | --help  Prints this help text

----

.Execution
[source, sh-session]
----
$ ./http2cli -t my-cli-tool -p 8080
2020/11/03 13:43:03 Starting server
----

== Endpoints

`/`::
  Returns basic information about the server, such as uptime and configured
  tools.
`/jobs/\{tool}/\{job-id}`::
  `\{tool}`: The name of the CLI tool to call +
  `\{job-id}`: A user provided job-id for this request.  This value will
  determine the location of the job output on the host machine. +
+
This endpoint attempts to execute the provided `\{tool}` on the host machine. +
If starting the tool fails, this endpoint will immediately return a `500`
error. +
+
If the tool starts successfully, this endpoint will return a `200`.  This does
not indicate that the job itself completed successfully, this simply means there
was no error with the initial CLI call.






== License

--
Copyright 2020 VEuPathDB

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
--